@friendId = 1

### Create friend
POST {{base_url}}/friends
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "john_doe",
  "name": "John"
}

### List friends
GET {{base_url}}/friends
Authorization: Bearer {{auth_token}}

### Get friend by ID
GET {{base_url}}/friends/{{friendId}}
Authorization: Bearer {{auth_token}}

### Update friend
PUT {{base_url}}/friends/{{friendId}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "John Doe"
}

### Delete friend
DELETE {{base_url}}/friends/{{friendId}}
Authorization: Bearer {{auth_token}}
