apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gomessenger.fullname" . }}-secrets
  labels:
    {{- include "gomessenger.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  JWT_SECRET_PREVIOUS: {{ .Values.secrets.jwtSecretPrevious | quote }}
  INTERNAL_SERVICE_TOKEN: {{ .Values.secrets.internalServiceToken | quote }}
  MEDIA_STORAGE_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | quote }}
  MEDIA_STORAGE_SECRET_KEY: {{ .Values.secrets.minioSecretKey | quote }}
